version: 1.0.{build}

configuration:
- Release
- Debug

before_build:
- cmd: cd src
- cmd: dotnet restore
- cmd: cd ..

build:
  verbosity: quiet

test_script:
- cmd: cd src/PolarisTests
- cmd: dotnet restore
- cmd: dotnet build
- cmd: dotnet test
- cmd: cd ..